name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU}}
          heroku_app_name: "hostguest-backend" #Must be unique in Heroku
          heroku_email: "dankatdennis@gmail.com"